#-> OpenGL window
/vis/open OGL 600x600-0+0

###########################
#-> Disable auto refresh and quieten vis messages
#-> whilst the macro does is job:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
###########################
#-> Draw geometry
/vis/drawVolume
###########################
#-> ADDITIONAL SETTINGS
/vis/set/lineWidth 100
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setLineWidth 15
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 3
/vis/modeling/trajectories/drawByParticleID-0/set alpha blue
/vis/modeling/trajectories/drawByParticleID-0/set Pb206 red
/vis/modeling/trajectories/drawByParticleID-0/set e- yellow
/vis/scene/endOfEventAction accumulate
/vis/scene/add/hits
/vis/viewer/set/viewpointVector 0 0 1
/vis/viewer/set/lightsVector 0 0 1
###########################
#-> Specify style
/vis/viewer/set/style surface
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100
###########################
#-> Make the world box invisible
#/vis/geometry/set/visibility World 0 false
#-> Re-establish auto-refreshing and verbosity
/vis/viewer/set/autoRefresh true
#/vis/verbose warnings